import { createContext, useState, useContext, ReactNode } from 'react';

type LanguageContextType = {
  language: 'en' | 'vi';
  setLanguage: (language: 'en' | 'vi') => void;
  t: (key: string) => string;
};

const translations = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.movies': 'Movies',
    'nav.genres': 'Genres',
    'nav.myList': 'My List',
    'nav.trending': 'Trending',
    'nav.search': 'Search',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'profile.myAccount': 'My Account',
    'profile.myProfile': 'My Profile',
    'search.placeholder': 'Search...',
    'search.button': 'Go',
    'nav.admin': 'Admin',
    
    // Home page
    'home.featured': 'Featured',
    'home.newReleases': 'New Releases',
    'loading.movies': 'Loading movies...',
    'error.title': 'Oops!',
    'error.movies': 'We encountered an error while loading movies. Please try again later.',
    'genres.action': 'Action',
    'home.premiumContent': 'Premium Content',
    'home.premiumDescription': 'Get access to exclusive trending movies and early releases with our premium membership.',
    'home.upgradeNow': 'Upgrade Now',
    'home.viewTrending': 'View Trending',
    
    // Movie details
    'movie.cast': 'Cast',
    'movie.director': 'Director',
    'movie.play': 'Play',
    'movie.addToList': 'Add to My List',
    'movie.similar': 'Similar Movies',
    
    // Premium content
    'premium.title': 'Premium Membership',
    'premium.description': 'Get access to exclusive content and features',
    'premium.member': 'You are a Premium Member!',
    'premium.expiry': 'Your premium membership is active until',
    'premium.benefits': 'Enjoy exclusive access to trending movies, VIP membership, and 24/7 support.',
    'premium.upgrade': 'Upgrade to Premium',
    'premium.cost': 'Get exclusive access to premium content and features for only',
    'premium.perMonth': 'per month',
    'premium.benefit1': 'Access to trending and hottest movies',
    'premium.benefit2': 'VIP membership with early access to new releases',
    'premium.benefit3': '24/7 priority customer support',
    'premium.currentBalance': 'Your current balance:',
    'premium.insufficientFunds': 'You need at least 100 USDT to upgrade to premium. Please deposit more funds.',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.userInfo': 'User Information',
    'profile.userDetails': 'Your account details and membership status',
    'profile.username': 'Username',
    'profile.email': 'Email',
    'profile.notSet': 'Not set',
    'profile.membership': 'Membership',
    'profile.normal': 'Normal',
    'profile.premium': 'Premium',
    'profile.viewPremium': 'View Premium Content',
    'profile.premiumExpires': 'Premium Expires',
    
    // Wallet
    'wallet.title': 'USDT Wallet',
    'wallet.description': 'Manage your crypto wallet and deposit funds',
    'wallet.currentBalance': 'Current Balance',
    'wallet.address': 'USDT Wallet Address (TRC20)',
    'wallet.enterAddress': 'Enter your USDT wallet address',
    'wallet.update': 'Update Wallet Address',
    'wallet.deposit': 'Deposit USDT',
    'wallet.amount': 'Amount (USDT)',
    'wallet.enterAmount': 'Enter amount to deposit',
    'wallet.hash': 'Transaction Hash',
    'wallet.enterHash': 'Enter the USDT transaction hash',
    'wallet.depositFunds': 'Deposit Funds',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.loginButton': 'Sign In',
    'auth.registerButton': 'Sign Up',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.haveAccount': 'Already have an account?',
    'auth.googleLogin': 'Sign in with Google',
    
    // Trending
    'trending.title': 'Trending Movies',
    'trending.premium': 'Premium Content',
    'trending.description': 'Exclusive content for premium members',
    
    // Google Drive
    'drive.title': 'Movies from Google Drive',
    'drive.description': 'Watch movies shared through Google Drive directly on FilmFlex',
    'drive.noMovies': 'No movies found',
    'drive.checkLink': 'Check that the Google Drive folder contains video files and is publicly accessible',
    'drive.needAccess': 'The folder might not be shared publicly. Try another folder ID or contact support.',
    'drive.sampleContent': 'Sample Movies',
    'drive.sampleDescription': 'While waiting for your Drive content, you can explore these sample movies',
    'error.googleDrive': 'There was an error accessing the Google Drive folder. Make sure the folder is publicly shared and contains video files.',
    'actions.retry': 'Retry',
    'actions.backHome': 'Back to Home',
    'nav.driveMovies': 'Drive Movies',
    
    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.users': 'Users',
    'admin.movies': 'Movies',
    'admin.financial': 'Financial',
    'admin.activity': 'Activity',
    'admin.activityLogs': 'Activity Logs',
    'admin.unauthorized': 'Unauthorized',
    'admin.adminAccessRequired': 'Admin access is required to view this page',
    'admin.loggedInAs': 'Logged in as',
    'admin.adminRole': 'Admin',
    'admin.subAdminRole': 'Sub-Admin',
    'admin.totalUsers': 'Total Users',
    'admin.totalMovies': 'Total Movies',
    'admin.pendingTransactions': 'Pending Transactions',
    'admin.recentActivity': 'Recent Activity',
    'admin.transactions': 'Transactions',
    'admin.userManagement': 'User Management',
    'admin.movieManagement': 'Movie Management',
    'admin.financialManagement': 'Financial Management',
    'admin.createNewUser': 'Create New User',
    'admin.createUserDescription': 'Add a new user to the system',
    'admin.userDetails': 'User Details',
    'admin.role': 'Role',
    'admin.userRole': 'User',
    'admin.type': 'Type',
    'admin.status': 'Status',
    'admin.actions': 'Actions',
    'admin.id': 'ID',
    'admin.createdAt': 'Created At',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.userListCaption': 'A list of all users in the system',
    'admin.noUsersFound': 'No users found',
    'admin.selectRole': 'Select Role',
    'admin.normalUser': 'Normal User',
    'admin.premiumUser': 'Premium User',
    'admin.selectUserType': 'Select User Type',
    'admin.deactivateUser': 'Deactivate',
    'admin.activateUser': 'Activate',
    'admin.userStatus': 'User Status',
    'admin.allRoles': 'All Roles',
    'admin.allStatuses': 'All Statuses',
    'admin.clearFilters': 'Clear Filters',
    'admin.activeUsers': 'Active Users',
    'admin.inactiveUsers': 'Inactive Users',
    'admin.editUser': 'Edit User',
    'admin.editUserDescription': 'Modify user details and roles',
    'admin.close': 'Close',
    'admin.cancel': 'Cancel',
    'admin.createUser': 'Create User',
    'admin.userUpdated': 'User Updated',
    'admin.userRoleUpdated': 'User role has been updated successfully',
    'admin.error': 'Error',
    'admin.userUpdateFailed': 'Failed to update user',
    'admin.userDeactivated': 'User Deactivated',
    'admin.userReactivated': 'User Reactivated',
    'admin.allActions': 'All Actions',
    'admin.resetFilters': 'Reset Filters',
    'admin.activityLogsCaption': 'A record of admin activities in the system',
    'admin.noLogsFound': 'No activity logs found',
    'admin.timestamp': 'Timestamp',
    'admin.adminUser': 'Admin User',
    'admin.action': 'Action',
    'admin.target': 'Target',
    'admin.details': 'Details',
    'admin.loadMoreLogs': 'Load More',
    'admin.sortOrder': 'Sort Order',
    'admin.newest': 'Newest First',
    'admin.oldest': 'Oldest First',
    'admin.amount': 'Amount',
    'admin.date': 'Date',
    'admin.method': 'Method',
    'admin.process': 'Process',
    'admin.totalIncome': 'Total Income',
    'admin.subscriptions': 'Subscriptions',
    'admin.deposits': 'Deposits',
    'admin.noPendingTransactions': 'No pending transactions',
    'admin.allTransactions': 'All Transactions',
    'admin.transactionsListCaption': 'A list of all financial transactions',
    'admin.noTransactionsFound': 'No transactions found',
    'admin.processTransaction': 'Process Transaction',
    'admin.processTransactionDescription': 'Review and update the status of this transaction',
    'admin.transactionId': 'Transaction ID',
    'admin.user': 'User',
    'admin.paymentMethod': 'Payment Method',
    'admin.currentStatus': 'Current Status',
    'admin.updateStatus': 'Update Status',
    'admin.selectStatus': 'Select Status',
    'admin.statusCompleted': 'Completed',
    'admin.statusFailed': 'Failed',
    'admin.statusRefunded': 'Refunded',
    'admin.processingNotes': 'Processing Notes',
    'admin.notesPlaceholder': 'Enter any notes about this transaction',
    'admin.confirm': 'Confirm',
    'admin.transactionProcessed': 'Transaction Processed',
    'admin.transactionProcessedSuccess': 'The transaction has been processed successfully',
    'admin.transactionProcessFailed': 'Failed to process transaction',
    'admin.userId': 'User ID',
    'admin.general.backToHome': 'Back to Home',
    'admin.filters': 'Filters',
    'admin.adminIdPlaceholder': 'Enter admin ID',
    'admin.movieUploads': 'Movie Uploads',
    'admin.pendingUploads': 'Pending Uploads',
    'admin.approvedUploads': 'Approved Uploads',
    'admin.rejectedUploads': 'Rejected Uploads',
    'admin.submitUpload': 'Submit Upload',
    'admin.uploaderId': 'Uploader ID',
    'admin.submittedAt': 'Submitted At',
    'admin.uploadsListCaption': 'A list of all movie uploads',
    'admin.noUploadsFound': 'No uploads found',
    'admin.addNewMovie': 'Add New Movie',
    'admin.addMovieDescription': 'Add a new movie to the catalog',
    'admin.addMovie': 'Add Movie',
    'admin.editMovie': 'Edit Movie',
    'admin.editMovieDescription': 'Edit movie details',
    'admin.posterUrl': 'Poster URL',
    'admin.backdropUrl': 'Backdrop URL',
    'admin.selectRating': 'Select Rating',
    'admin.commaSeparated': 'comma separated',
    'admin.createMovie': 'Create Movie',
    'admin.deleteMovie': 'Delete Movie',
    'admin.deleteMovieConfirmation': 'Are you sure you want to delete this movie? This action cannot be undone.',
    'admin.moviesListCaption': 'A list of all movies in the database',
    'admin.noMoviesFound': 'No movies found',
    'admin.views': 'Views',
    'admin.title': 'Title',
    'admin.releaseYear': 'Release Year',
    'admin.duration': 'Duration',
    'admin.description': 'Description',
    'admin.director': 'Director',
    'admin.cast': 'Cast',
    'admin.videoUrl': 'Video URL',
    'admin.copyFromDrive': 'Copy from Drive',
    'admin.addFromUrl': 'Add from URL',
    'admin.copyMovieDescription': 'Copy a movie from a public Google Drive folder to the website',
    'admin.sourceFolderUrl': 'Source Folder URL',
    'admin.destinationFolder': 'Destination Folder',
    'admin.copyMovie': 'Copy Movie',
    'admin.copyingMovie': 'Copying Movie...',
    'admin.movieCopied': 'Movie Copied Successfully',
    'admin.copyFailed': 'Failed to copy movie',
    'admin.enterSourceUrl': 'Enter source Google Drive folder URL',
    'admin.selectDestination': 'Select destination folder',
    'admin.copyFromDriveDescription': 'Copy movies from a Google Drive folder to the website',
    'admin.sourceFolderId': 'Source Folder ID',
    'admin.sourceFolderIdHint': 'The ID from a public Google Drive folder that contains movies',
    'admin.destinationFolderId': 'Destination Folder ID',
    'admin.destinationFolderIdHint': 'The ID of the Google Drive folder where movies will be copied to',
    'admin.copyMovies': 'Copy Movies',
    'admin.driveMoviesCopied': 'Drive Movies Copied',
    'admin.driveMoviesCopiedSuccess': 'Successfully copied {count} movies from Drive',
    'admin.driveMoviesCopyFailed': 'Failed to copy movies from Drive',
    'admin.creating': 'Creating...',
    'admin.movieCreated': 'Movie Created',
    'admin.movieCreatedSuccess': 'Movie has been created successfully',
  },
  vi: {
    // Navbar
    'nav.home': 'Trang chủ',
    'nav.movies': 'Phim',
    'nav.genres': 'Thể loại',
    'nav.myList': 'Danh sách của tôi',
    'nav.trending': 'Xu hướng',
    'nav.search': 'Tìm kiếm',
    'nav.profile': 'Hồ sơ',
    'nav.login': 'Đăng nhập',
    'nav.logout': 'Đăng xuất',
    'profile.myAccount': 'Tài khoản của tôi',
    'profile.myProfile': 'Hồ sơ của tôi',
    'search.placeholder': 'Tìm kiếm...',
    'search.button': 'Đi',
    'nav.admin': 'Quản trị',
    
    // Home page
    'home.featured': 'Nổi bật',
    'home.newReleases': 'Phim mới',
    'loading.movies': 'Đang tải phim...',
    'error.title': 'Rất tiếc!',
    'error.movies': 'Đã xảy ra lỗi khi tải phim. Vui lòng thử lại sau.',
    'genres.action': 'Hành động',
    'home.premiumContent': 'Nội dung cao cấp',
    'home.premiumDescription': 'Truy cập các phim xu hướng độc quyền và phát hành sớm với tư cách thành viên cao cấp.',
    'home.upgradeNow': 'Nâng cấp ngay',
    'home.viewTrending': 'Xem xu hướng',
    
    // Movie details
    'movie.cast': 'Diễn viên',
    'movie.director': 'Đạo diễn',
    'movie.play': 'Phát',
    'movie.addToList': 'Thêm vào danh sách',
    'movie.similar': 'Phim tương tự',
    
    // Premium content
    'premium.title': 'Tư cách thành viên cao cấp',
    'premium.description': 'Truy cập nội dung và tính năng độc quyền',
    'premium.member': 'Bạn là thành viên cao cấp!',
    'premium.expiry': 'Tư cách thành viên cao cấp của bạn có hiệu lực đến',
    'premium.benefits': 'Tận hưởng quyền truy cập độc quyền vào phim xu hướng, tư cách thành viên VIP và hỗ trợ 24/7.',
    'premium.upgrade': 'Nâng cấp lên cao cấp',
    'premium.cost': 'Nhận quyền truy cập độc quyền vào nội dung và tính năng cao cấp chỉ với',
    'premium.perMonth': 'mỗi tháng',
    'premium.benefit1': 'Truy cập vào các phim xu hướng và hot nhất',
    'premium.benefit2': 'Tư cách thành viên VIP với quyền truy cập sớm vào các bản phát hành mới',
    'premium.benefit3': 'Hỗ trợ khách hàng ưu tiên 24/7',
    'premium.currentBalance': 'Số dư hiện tại của bạn:',
    'premium.insufficientFunds': 'Bạn cần ít nhất 100 USDT để nâng cấp lên cao cấp. Vui lòng nạp thêm tiền.',
    
    // Profile
    'profile.title': 'Hồ sơ của tôi',
    'profile.userInfo': 'Thông tin người dùng',
    'profile.userDetails': 'Chi tiết tài khoản và trạng thái thành viên của bạn',
    'profile.username': 'Tên người dùng',
    'profile.email': 'Email',
    'profile.notSet': 'Chưa đặt',
    'profile.membership': 'Tư cách thành viên',
    'profile.normal': 'Thường',
    'profile.premium': 'Cao cấp',
    'profile.viewPremium': 'Xem nội dung cao cấp',
    'profile.premiumExpires': 'Cao cấp hết hạn',
    
    // Wallet
    'wallet.title': 'Ví USDT',
    'wallet.description': 'Quản lý ví tiền điện tử và nạp tiền của bạn',
    'wallet.currentBalance': 'Số dư hiện tại',
    'wallet.address': 'Địa chỉ ví USDT (TRC20)',
    'wallet.enterAddress': 'Nhập địa chỉ ví USDT của bạn',
    'wallet.update': 'Cập nhật địa chỉ ví',
    'wallet.deposit': 'Nạp USDT',
    'wallet.amount': 'Số tiền (USDT)',
    'wallet.enterAmount': 'Nhập số tiền cần nạp',
    'wallet.hash': 'Mã giao dịch',
    'wallet.enterHash': 'Nhập mã giao dịch USDT',
    'wallet.depositFunds': 'Nạp tiền',
    
    // Auth
    'auth.login': 'Đăng nhập',
    'auth.register': 'Đăng ký',
    'auth.username': 'Tên người dùng',
    'auth.password': 'Mật khẩu',
    'auth.confirmPassword': 'Xác nhận mật khẩu',
    'auth.loginButton': 'Đăng nhập',
    'auth.registerButton': 'Đăng ký',
    'auth.noAccount': 'Chưa có tài khoản?',
    'auth.haveAccount': 'Đã có tài khoản?',
    'auth.googleLogin': 'Đăng nhập bằng Google',
    
    // Trending
    'trending.title': 'Phim xu hướng',
    'trending.premium': 'Nội dung cao cấp',
    'trending.description': 'Nội dung độc quyền cho thành viên cao cấp',
    
    // Google Drive
    'drive.title': 'Phim từ Google Drive',
    'drive.description': 'Xem phim được chia sẻ qua Google Drive trực tiếp trên FilmFlex',
    'drive.noMovies': 'Không tìm thấy phim',
    'drive.checkLink': 'Kiểm tra xem thư mục Google Drive có chứa tệp video và có thể truy cập công khai',
    'drive.needAccess': 'Thư mục có thể không được chia sẻ công khai. Hãy thử một ID thư mục khác hoặc liên hệ hỗ trợ.',
    'drive.sampleContent': 'Phim mẫu',
    'drive.sampleDescription': 'Trong khi đợi nội dung Drive của bạn, bạn có thể khám phá những bộ phim mẫu này',
    'error.googleDrive': 'Đã xảy ra lỗi khi truy cập thư mục Google Drive. Đảm bảo thư mục được chia sẻ công khai và chứa các tệp video.',
    'actions.retry': 'Thử lại',
    'actions.backHome': 'Quay lại trang chủ',
    'nav.driveMovies': 'Phim Drive',
    
    // Admin Dashboard
    'admin.dashboard': 'Bảng Điều Khiển Quản Trị',
    'admin.users': 'Người Dùng',
    'admin.movies': 'Phim',
    'admin.financial': 'Tài Chính',
    'admin.activity': 'Hoạt Động',
    'admin.activityLogs': 'Nhật Ký Hoạt Động',
    'admin.unauthorized': 'Không Được Phép',
    'admin.adminAccessRequired': 'Cần có quyền quản trị để xem trang này',
    'admin.loggedInAs': 'Đăng nhập với tư cách',
    'admin.adminRole': 'Quản Trị Viên',
    'admin.subAdminRole': 'Phó Quản Trị',
    'admin.totalUsers': 'Tổng Người Dùng',
    'admin.totalMovies': 'Tổng Số Phim',
    'admin.pendingTransactions': 'Giao Dịch Đang Chờ',
    'admin.recentActivity': 'Hoạt Động Gần Đây',
    'admin.transactions': 'Giao Dịch',
    'admin.userManagement': 'Quản Lý Người Dùng',
    'admin.movieManagement': 'Quản Lý Phim',
    'admin.financialManagement': 'Quản Lý Tài Chính',
    'admin.createNewUser': 'Tạo Người Dùng Mới',
    'admin.createUserDescription': 'Thêm người dùng mới vào hệ thống',
    'admin.userDetails': 'Chi Tiết Người Dùng',
    'admin.role': 'Vai Trò',
    'admin.userRole': 'Người Dùng',
    'admin.type': 'Loại',
    'admin.status': 'Trạng Thái',
    'admin.actions': 'Hành Động',
    'admin.id': 'ID',
    'admin.createdAt': 'Được Tạo Lúc',
    'admin.active': 'Hoạt Động',
    'admin.inactive': 'Không Hoạt Động',
    'admin.userListCaption': 'Danh sách tất cả người dùng trong hệ thống',
    'admin.noUsersFound': 'Không tìm thấy người dùng',
    'admin.selectRole': 'Chọn Vai Trò',
    'admin.normalUser': 'Người Dùng Thường',
    'admin.premiumUser': 'Người Dùng Cao Cấp',
    'admin.selectUserType': 'Chọn Loại Người Dùng',
    'admin.deactivateUser': 'Hủy Kích Hoạt',
    'admin.activateUser': 'Kích Hoạt',
    'admin.userStatus': 'Trạng Thái Người Dùng',
    'admin.allRoles': 'Tất Cả Vai Trò',
    'admin.allStatuses': 'Tất Cả Trạng Thái',
    'admin.clearFilters': 'Xóa Bộ Lọc',
    'admin.activeUsers': 'Người Dùng Đang Hoạt Động',
    'admin.inactiveUsers': 'Người Dùng Không Hoạt Động',
    'admin.editUser': 'Chỉnh Sửa Người Dùng',
    'admin.editUserDescription': 'Sửa đổi chi tiết và vai trò người dùng',
    'admin.close': 'Đóng',
    'admin.cancel': 'Hủy',
    'admin.createUser': 'Tạo Người Dùng',
    'admin.userUpdated': 'Người Dùng Đã Cập Nhật',
    'admin.userRoleUpdated': 'Vai trò người dùng đã được cập nhật thành công',
    'admin.error': 'Lỗi',
    'admin.userUpdateFailed': 'Không thể cập nhật người dùng',
    'admin.userDeactivated': 'Người Dùng Đã Bị Hủy Kích Hoạt',
    'admin.userReactivated': 'Người Dùng Đã Được Kích Hoạt Lại',
    'admin.allActions': 'Tất Cả Hành Động',
    'admin.resetFilters': 'Đặt Lại Bộ Lọc',
    'admin.activityLogsCaption': 'Bản ghi các hoạt động quản trị trong hệ thống',
    'admin.noLogsFound': 'Không tìm thấy nhật ký hoạt động',
    'admin.timestamp': 'Thời Gian',
    'admin.adminUser': 'Người Quản Trị',
    'admin.action': 'Hành Động',
    'admin.target': 'Mục Tiêu',
    'admin.details': 'Chi Tiết',
    'admin.loadMoreLogs': 'Tải Thêm',
    'admin.sortOrder': 'Thứ Tự Sắp Xếp',
    'admin.newest': 'Mới Nhất Trước',
    'admin.oldest': 'Cũ Nhất Trước',
    'admin.amount': 'Số Tiền',
    'admin.date': 'Ngày',
    'admin.method': 'Phương Thức',
    'admin.process': 'Xử Lý',
    'admin.totalIncome': 'Tổng Thu Nhập',
    'admin.subscriptions': 'Đăng Ký',
    'admin.deposits': 'Nạp Tiền',
    'admin.noPendingTransactions': 'Không có giao dịch đang chờ',
    'admin.allTransactions': 'Tất Cả Giao Dịch',
    'admin.transactionsListCaption': 'Danh sách tất cả các giao dịch tài chính',
    'admin.noTransactionsFound': 'Không tìm thấy giao dịch',
    'admin.processTransaction': 'Xử Lý Giao Dịch',
    'admin.processTransactionDescription': 'Xem xét và cập nhật trạng thái của giao dịch này',
    'admin.transactionId': 'ID Giao Dịch',
    'admin.user': 'Người Dùng',
    'admin.paymentMethod': 'Phương Thức Thanh Toán',
    'admin.currentStatus': 'Trạng Thái Hiện Tại',
    'admin.updateStatus': 'Cập Nhật Trạng Thái',
    'admin.selectStatus': 'Chọn Trạng Thái',
    'admin.statusCompleted': 'Hoàn Thành',
    'admin.statusFailed': 'Thất Bại',
    'admin.statusRefunded': 'Hoàn Tiền',
    'admin.processingNotes': 'Ghi Chú Xử Lý',
    'admin.notesPlaceholder': 'Nhập bất kỳ ghi chú nào về giao dịch này',
    'admin.confirm': 'Xác Nhận',
    'admin.transactionProcessed': 'Giao Dịch Đã Xử Lý',
    'admin.transactionProcessedSuccess': 'Giao dịch đã được xử lý thành công',
    'admin.transactionProcessFailed': 'Không thể xử lý giao dịch',
    'admin.userId': 'ID Người Dùng',
    'admin.general.backToHome': 'Quay Lại Trang Chủ',
    'admin.filters': 'Bộ Lọc',
    'admin.adminIdPlaceholder': 'Nhập ID quản trị',
    'admin.movieUploads': 'Tải Lên Phim',
    'admin.pendingUploads': 'Tải Lên Đang Chờ',
    'admin.approvedUploads': 'Tải Lên Đã Duyệt',
    'admin.rejectedUploads': 'Tải Lên Bị Từ Chối',
    'admin.submitUpload': 'Gửi Tải Lên',
    'admin.uploaderId': 'ID Người Tải Lên',
    'admin.submittedAt': 'Gửi Lúc',
    'admin.uploadsListCaption': 'Danh sách tất cả các phim được tải lên',
    'admin.noUploadsFound': 'Không tìm thấy tải lên nào',
    'admin.addNewMovie': 'Thêm Phim Mới',
    'admin.addMovieDescription': 'Thêm một bộ phim mới vào danh mục',
    'admin.addMovie': 'Thêm Phim',
    'admin.editMovie': 'Chỉnh Sửa Phim',
    'admin.copyFromDrive': 'Sao chép từ Drive',
    'admin.addFromUrl': 'Thêm từ URL',
    'admin.copyFromDriveDescription': 'Sao chép phim từ thư mục Google Drive vào trang web',
    'admin.sourceFolderId': 'ID Thư mục nguồn',
    'admin.sourceFolderIdHint': 'ID của thư mục Google Drive công khai chứa phim',
    'admin.destinationFolderId': 'ID Thư mục đích',
    'admin.destinationFolderIdHint': 'ID của thư mục Google Drive nơi phim sẽ được sao chép đến',
    'admin.copyMovies': 'Sao chép phim',
    'admin.copyMovie': 'Sao chép phim',
    'admin.copyingMovie': 'Đang sao chép phim...',
    'admin.movieCopied': 'Phim đã sao chép thành công',
    'admin.copyFailed': 'Không thể sao chép phim',
    'admin.enterSourceUrl': 'Nhập URL thư mục Google Drive nguồn',
    'admin.selectDestination': 'Chọn thư mục đích',
    'admin.driveMoviesCopied': 'Đã sao chép phim từ Drive',
    'admin.driveMoviesCopiedSuccess': 'Đã sao chép thành công {count} phim từ Drive',
    'admin.driveMoviesCopyFailed': 'Không thể sao chép phim từ Drive',
    'admin.creating': 'Đang tạo...',
    'admin.movieCreated': 'Phim đã được tạo',
    'admin.movieCreatedSuccess': 'Phim đã được tạo thành công',
    'admin.editMovieDescription': 'Chỉnh sửa chi tiết phim',
    'admin.posterUrl': 'URL Poster',
    'admin.backdropUrl': 'URL Backdrop',
    'admin.selectRating': 'Chọn Xếp Hạng',
    'admin.commaSeparated': 'phân cách bởi dấu phẩy',
    'admin.createMovie': 'Tạo Phim',
    'admin.deleteMovie': 'Xóa Phim',
    'admin.deleteMovieConfirmation': 'Bạn có chắc chắn muốn xóa phim này? Hành động này không thể hoàn tác.',
    'admin.moviesListCaption': 'Danh sách tất cả các phim trong cơ sở dữ liệu',
    'admin.noMoviesFound': 'Không tìm thấy phim',
    'admin.views': 'Lượt Xem',
    'admin.title': 'Tiêu Đề',
    'admin.releaseYear': 'Năm Phát Hành',
    'admin.duration': 'Thời Lượng',
    'admin.description': 'Mô Tả',
    'admin.director': 'Đạo Diễn',
    'admin.cast': 'Diễn Viên',
    'admin.videoUrl': 'URL Video',
  }
};

export const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<'en' | 'vi'>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}